# Generated by Django 4.0.4 on 2022-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_user',
            field=models.CharField(max_length=3),
        ),
    ]
