# Generated by Django 4.0.4 on 2022-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_password_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
